name: Build Helm Chart

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Lint Helm chart
        run: helm lint .

      - name: Package Helm chart
        run: helm package .

      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@4.1.0
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: true